## Deliverable 2. Create a Customer Travel Destinations Map.

In [16]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [17]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Tasiilaq,GL,65.6145,-37.6368,32.16,99,100,3.85,snow
1,1,Ushuaia,AR,-54.8000,-68.3000,48.09,73,100,5.44,light rain
2,2,Avarua,CK,-21.2078,-159.7750,69.85,100,40,1.14,scattered clouds
3,3,Rikitea,PF,-23.1203,-134.9692,73.31,73,98,15.28,overcast clouds
4,4,San Jose,US,37.3394,-121.8950,64.69,67,1,0.00,mist

In [18]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 85

In [19]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
city_results_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
city_results_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Rikitea,PF,-23.1203,-134.9692,73.31,73,98,15.28,overcast clouds
12,12,Ugoofaaru,MV,5.6667,73.0000,81.86,79,100,20.09,overcast clouds
13,13,Atuona,PF,-9.8000,-139.0333,77.34,74,13,16.73,few clouds
14,14,Souillac,MU,-20.5167,57.5167,77.36,68,29,12.08,scattered clouds
27,27,Bengkulu,ID,-3.8004,102.2655,75.99,89,100,3.31,moderate rain
30,30,Vao,NC,-22.6667,167.4833,75.45,82,2,7.25,clear sky
31,31,Hithadhoo,MV,-0.6000,73.0833,82.11,75,41,8.86,scattered clouds
32,32,Hermanus,ZA,-34.4187,19.2345,75.79,69,96,8.84,overcast clouds
35,35,Puerto Escondido,MX,15.8500,-97.0667,83.82,43,16,2.04,few clouds
36,36,Puri,IN,19.8000,85.8500,75.72,88,34,10.47,scattered clouds

In [20]:
# 4a. Determine if there are any empty rows.
city_results_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [21]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
city_results_df = city_results_df.dropna()
city_results_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Rikitea,PF,-23.1203,-134.9692,73.31,73,98,15.28,overcast clouds
12,12,Ugoofaaru,MV,5.6667,73.0000,81.86,79,100,20.09,overcast clouds
13,13,Atuona,PF,-9.8000,-139.0333,77.34,74,13,16.73,few clouds
14,14,Souillac,MU,-20.5167,57.5167,77.36,68,29,12.08,scattered clouds
27,27,Bengkulu,ID,-3.8004,102.2655,75.99,89,100,3.31,moderate rain
...,...,...,...,...,...,...,...,...,...,...
686,686,Awjilah,LY,29.1081,21.2869,73.17,33,10,7.81,clear sky
689,689,Rio Grande,BR,-32.0350,-52.0986,76.24,62,100,11.45,light rain
693,693,Acapulco,MX,16.8634,-99.8901,80.42,54,1,6.91,clear sky
695,695,Bria,CF,6.5423,21.9863,75.88,78,73,3.60,light rain
696,696,Yenagoa,NG,4.9247,6.2642,80.64,83,92,5.70,moderate rain

In [22]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = city_results_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Rikitea,PF,73.31,overcast clouds,-23.1203,-134.9692,
12,Ugoofaaru,MV,81.86,overcast clouds,5.6667,73.0000,
13,Atuona,PF,77.34,few clouds,-9.8000,-139.0333,
14,Souillac,MU,77.36,scattered clouds,-20.5167,57.5167,
27,Bengkulu,ID,75.99,moderate rain,-3.8004,102.2655,
30,Vao,NC,75.45,clear sky,-22.6667,167.4833,
31,Hithadhoo,MV,82.11,scattered clouds,-0.6000,73.0833,
32,Hermanus,ZA,75.79,overcast clouds,-34.4187,19.2345,
35,Puerto Escondido,MX,83.82,few clouds,15.8500,-97.0667,
36,Puri,IN,75.72,scattered clouds,19.8000,85.8500,

In [26]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    lng = row['Lng']
    
    params['location'] = f"{lat},{lng}"
        
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
      hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [28]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df = hotel_df.dropna()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Rikitea,PF,73.31,overcast clouds,-23.1203,-134.9692,People ThankYou
12,Ugoofaaru,MV,81.86,overcast clouds,5.6667,73.0000,Ungoofaaru Inn
13,Atuona,PF,77.34,few clouds,-9.8000,-139.0333,Villa Enata
14,Souillac,MU,77.36,scattered clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
27,Bengkulu,ID,75.99,moderate rain,-3.8004,102.2655,Grage Hotel Bengkulu
...,...,...,...,...,...,...,...
686,Awjilah,LY,73.17,clear sky,29.1081,21.2869,
689,Rio Grande,BR,76.24,light rain,-32.0350,-52.0986,Hotel Atlântico Rio Grande
693,Acapulco,MX,80.42,clear sky,16.8634,-99.8901,HS Hotsson Smart Acapulco
695,Bria,CF,75.88,light rain,6.5423,21.9863,
696,Yenagoa,NG,80.64,moderate rain,4.9247,6.2642,Aridolf Resort Wellness and Spa

In [29]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [30]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))